version: '2'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookupd
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "4171:4171"
    links:
      - nsqlookupd
  #redis:
  #  image: redis
  #  ports:
  #    - "6379:6379"
  #
  app:
    build: .
    restart: always
    #environment:
    # - ELASTIC_HOSTS=elasticsearch:9200
    ports:
     - "30701:9000"
    links:
     - nsqlookupd
     - nsqd
    command: ["./app"]

