version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq:v1.1.0
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq:v1.1.0
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    volumes:
     - /docker/nsq/data:/data
    ports:
      - "4150:4150"
      - "4151:4151"
     
  nsqadmin:
    image: nsqio/nsq:v1.1.0
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
      
  goapp:
    build: .
    restart: always
    depends_on:
      - nsqlookupd
    environment:
     - NSQD_IP=nsqd
     - LOOKUP_IP=nsqlookupd
    ports:
     - "9002:9002"
    links:
     - nsqlookupd
     - nsqd
    #command: ["/sync-service"]

